import _ from "lodash";
import {
  PUBLICATION_FETCH,
  PUBLICATION_FETCH_SUCCESS,
  PUBLICATION_FETCH_FAILURE,
  PUBLICATION_INQUIRY,
  PUBLICATION_INQUIRY_SUCCESS,
  PUBLICATION_INQUIRY_FAILURE,
} from "./actionTypes.js";

export const fetch = {
  types: [PUBLICATION_FETCH, PUBLICATION_FETCH_SUCCESS, PUBLICATION_FETCH_FAILURE],
};

export const inquiry = {
  path: "/inquiry",
  method: "POST",
  types: [PUBLICATION_INQUIRY, PUBLICATION_INQUIRY_SUCCESS, PUBLICATION_INQUIRY_FAILURE],
};
