---
- hosts: all
  remote_user: "{{ root_user }}"
  gather_facts: False
  tasks:
    - name: python installed (Ansible requirement)
      raw: "apt-get -y install python"
      become: True
      tags:
        - remote

- hosts: all
  remote_user: "{{ root_user }}"
  roles:
    - role: common.remote
      tags:
        -  remote

- hosts: all
  remote_user: "{{ user }}"
  roles:
    - role: common
    - role: ruby
    - role: webserver
      static: False
    - role: dbserver

- include: deploy.yml
